Email service
wiredsandbox/fundli pull request #32
Opened 2023-03-30 15:11 UTC by blacdev

2023-03-30 15:22 UTC, thealamu requested changes

2023-03-30 15:22 UTC, thealamu commented on fundli/database/account.py
> +                verification_code=data.get("verification_code"),
`verification_code` is vague, we could need a verification code for password-reset, email-reset, and so on

2023-03-30 15:22 UTC, thealamu commented on fundli/services/account.py
> +    update_query = {"password": hash_password(password)}
Can we do a full account update/replace?

2023-04-01 11:47 UTC, thealamu requested changes

2023-04-01 11:47 UTC, thealamu commented on fundli/account.py
> +@account_router.get("/forgot-password", response_model=EmailResponse)
Should this be a POST?

2023-04-01 11:47 UTC, thealamu commented on fundli/services/account.py
> +    account_update = {"password": hash_password(password)}
Similar to other service functions that do an update, let's pass the account down from the router, update the specific field and do an entire update using `find_one_and_replace`

2023-04-02 14:44 UTC, blacdev commented on fundli/database/database.py
> +        self.collection.update_one(query_filter, {"$set": data})
No but i have renamed the method to `fine_one_and_replace` . IT function remains the same. I am also changing the the implementation to take the object as suggested

2023-04-02 14:46 UTC, blacdev commented on fundli/account.py
> +@account_router.get("/forgot-password", response_model=EmailResponse)
Yes. It has also been fixed

2023-04-02 15:33 UTC, thealamu requested changes

2023-04-02 15:33 UTC, thealamu commented on fundli/services/account.py
> +    account, error = get_account(email)
Update looks good but can we receive the account from the route as opposed to fetching it here. Single Responsibility Principle

2023-04-02 15:33 UTC, thealamu commented on fundli/database/database.py
> +        self.collection.update_one(query_filter, {"$set": data})
This call should be a find_one_and_replace for the setup to work

2023-04-02 15:33 UTC, thealamu commented on fundli/services/account.py
> +        account_database.find_one_and_replace(query, account.to_dict())
So we can keep the database method name as “update”, it just does a find_one_and_replace internally

2023-04-02 15:37 UTC, blacdev commented on fundli/database/database.py
> +        self.collection.update_one(query_filter, {"$set": data})
It works. I already tested it. Maybe more context would help me see what is wrong here

2023-04-02 15:38 UTC, blacdev commented on fundli/services/account.py
> +        account_database.find_one_and_replace(query, account.to_dict())
now you lost me

2023-04-03 13:51 UTC, thealamu approved these changes

2023-04-03 13:51 UTC, thealamu commented on fundli/services/account.py
> +        account_database.update(old_account_obj.to_dict(), account.to_dict())
Please use a queryfilter that targets the account's id as opposed to the entire `old_account_obj` object here

2023-04-03 14:08 UTC, merged